[tox]
# List all versions you want to support here
envlist = py38, py310

[gh-actions]
# This maps the GitHub Matrix version to the Tox environment
python = 
    3.8: py38
    3.10: py310

[testenv]
deps = -rrequirements_dev.txt
commands =
    # 1. Linting: Stop for syntax errors
    flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
    # 2. Linting: Complexity warnings
    flake8 src --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    # 3. Type Checking
    mypy src/
    # 4. Unit Tests
    pytest -v tests/unit
    # 5. Integration Tests
    pytest -v tests/integration